#!/bin/sh

set -e
#set -x

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst.mysql

dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_mysql_createdb_encoding="utf8mb4"
dbc_generate_include=php:/etc/roylabcon/debian-db.php
dbc_go roylabcon "$@"

